"""add avatar field

Revision ID: 3cddfa3cf402
Revises: 59fcb540bb30
Create Date: 2025-04-16 12:16:04.493191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cddfa3cf402'
down_revision = '59fcb540bb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('t_product_attrs_ibfk_2', table_name='t_product_attrs')  # 移除这行可能导致错误的代码
    op.add_column('t_users', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_users', 'avatar')
    # op.create_index('t_product_attrs_ibfk_2', 't_product_attrs', ['product_id'], unique=False)  # 移除这行相应的恢复代码
    # ### end Alembic commands ###
