"""empty message

Revision ID: 53bac7229757
Revises: a9835af79fda
Create Date: 2024-11-14 14:37:03.769385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53bac7229757'
down_revision = 'a9835af79fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_roles_menus',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['t_menus.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['t_roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_roles_menus')
    # ### end Alembic commands ###
