"""empty message

Revision ID: 544e11893031
Revises: fcd3615ea8ca
Create Date: 2024-11-13 10:22:05.595911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544e11893031'
down_revision = 'fcd3615ea8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_roles')
    # ### end Alembic commands ###
