"""initial migration

Revision ID: 59fcb540bb30
Revises: 
Create Date: 2025-04-16 11:45:20.363025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fcb540bb30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('t_attributes_ibfk_1', 't_attributes', type_='foreignkey')
    op.create_foreign_key(None, 't_attributes', 't_categories', ['category_id'], ['id'])
    op.drop_constraint('t_categories_ibfk_1', 't_categories', type_='foreignkey')
    op.create_foreign_key(None, 't_categories', 't_categories', ['parent_id'], ['id'])
    op.drop_constraint('t_express_ibfk_1', 't_express', type_='foreignkey')
    op.create_foreign_key(None, 't_express', 't_orders', ['order_id'], ['id'])
    op.drop_constraint('t_menus_ibfk_1', 't_menus', type_='foreignkey')
    op.create_foreign_key(None, 't_menus', 't_menus', ['parent_id'], ['id'])
    op.drop_constraint('t_order_details_ibfk_1', 't_order_details', type_='foreignkey')
    op.drop_constraint('t_order_details_ibfk_2', 't_order_details', type_='foreignkey')
    op.create_foreign_key(None, 't_order_details', 't_products', ['product_id'], ['id'])
    op.create_foreign_key(None, 't_order_details', 't_orders', ['order_id'], ['id'])
    op.drop_constraint('t_orders_ibfk_1', 't_orders', type_='foreignkey')
    op.create_foreign_key(None, 't_orders', 't_users', ['user_id'], ['id'])
    op.drop_constraint('t_pictures_ibfk_1', 't_pictures', type_='foreignkey')
    op.create_foreign_key(None, 't_pictures', 't_products', ['product_id'], ['id'])
    op.drop_constraint('t_product_attrs_ibfk_1', 't_product_attrs', type_='foreignkey')
    op.drop_constraint('t_product_attrs_ibfk_2', 't_product_attrs', type_='foreignkey')
    op.create_foreign_key(None, 't_product_attrs', 't_products', ['product_id'], ['id'])
    op.create_foreign_key(None, 't_product_attrs', 't_attributes', ['attr_id'], ['id'])
    op.drop_constraint('t_products_ibfk_2', 't_products', type_='foreignkey')
    op.drop_constraint('t_products_ibfk_3', 't_products', type_='foreignkey')
    op.drop_constraint('t_products_ibfk_1', 't_products', type_='foreignkey')
    op.create_foreign_key(None, 't_products', 't_categories', ['cid_two'], ['id'])
    op.create_foreign_key(None, 't_products', 't_categories', ['cid_three'], ['id'])
    op.create_foreign_key(None, 't_products', 't_categories', ['cid_one'], ['id'])
    op.drop_constraint('t_roles_menus_ibfk_2', 't_roles_menus', type_='foreignkey')
    op.drop_constraint('t_roles_menus_ibfk_1', 't_roles_menus', type_='foreignkey')
    op.create_foreign_key(None, 't_roles_menus', 't_roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 't_roles_menus', 't_menus', ['menu_id'], ['id'])
    op.drop_constraint('t_skus_ibfk_1', 't_skus', type_='foreignkey')
    op.create_foreign_key(None, 't_skus', 't_products', ['product_id'], ['id'])
    op.drop_constraint('t_spec_templates_ibfk_1', 't_spec_templates', type_='foreignkey')
    op.create_foreign_key(None, 't_spec_templates', 't_categories', ['category_id'], ['id'])
    op.drop_constraint('t_stock_logs_ibfk_1', 't_stock_logs', type_='foreignkey')
    op.create_foreign_key(None, 't_stock_logs', 't_skus', ['sku_id'], ['id'])
    op.drop_constraint('t_users_ibfk_1', 't_users', type_='foreignkey')
    op.create_foreign_key(None, 't_users', 't_roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_users', type_='foreignkey')
    op.create_foreign_key('t_users_ibfk_1', 't_users', 't_roles', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 't_stock_logs', type_='foreignkey')
    op.create_foreign_key('t_stock_logs_ibfk_1', 't_stock_logs', 't_skus', ['sku_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_constraint(None, 't_spec_templates', type_='foreignkey')
    op.create_foreign_key('t_spec_templates_ibfk_1', 't_spec_templates', 't_categories', ['category_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 't_skus', type_='foreignkey')
    op.create_foreign_key('t_skus_ibfk_1', 't_skus', 't_products', ['product_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 't_roles_menus', type_='foreignkey')
    op.drop_constraint(None, 't_roles_menus', type_='foreignkey')
    op.create_foreign_key('t_roles_menus_ibfk_1', 't_roles_menus', 't_menus', ['menu_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('t_roles_menus_ibfk_2', 't_roles_menus', 't_roles', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 't_products', type_='foreignkey')
    op.drop_constraint(None, 't_products', type_='foreignkey')
    op.drop_constraint(None, 't_products', type_='foreignkey')
    op.create_foreign_key('t_products_ibfk_1', 't_products', 't_categories', ['cid_one'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('t_products_ibfk_3', 't_products', 't_categories', ['cid_two'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('t_products_ibfk_2', 't_products', 't_categories', ['cid_three'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 't_product_attrs', type_='foreignkey')
    op.drop_constraint(None, 't_product_attrs', type_='foreignkey')
    op.create_foreign_key('t_product_attrs_ibfk_2', 't_product_attrs', 't_products', ['product_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.create_foreign_key('t_product_attrs_ibfk_1', 't_product_attrs', 't_attributes', ['attr_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 't_pictures', type_='foreignkey')
    op.create_foreign_key('t_pictures_ibfk_1', 't_pictures', 't_products', ['product_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_constraint(None, 't_orders', type_='foreignkey')
    op.create_foreign_key('t_orders_ibfk_1', 't_orders', 't_users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 't_order_details', type_='foreignkey')
    op.drop_constraint(None, 't_order_details', type_='foreignkey')
    op.create_foreign_key('t_order_details_ibfk_2', 't_order_details', 't_products', ['product_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('t_order_details_ibfk_1', 't_order_details', 't_orders', ['order_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 't_menus', type_='foreignkey')
    op.create_foreign_key('t_menus_ibfk_1', 't_menus', 't_menus', ['parent_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 't_express', type_='foreignkey')
    op.create_foreign_key('t_express_ibfk_1', 't_express', 't_orders', ['order_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 't_categories', type_='foreignkey')
    op.create_foreign_key('t_categories_ibfk_1', 't_categories', 't_categories', ['parent_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 't_attributes', type_='foreignkey')
    op.create_foreign_key('t_attributes_ibfk_1', 't_attributes', 't_categories', ['category_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    # ### end Alembic commands ###
