"""empty message

Revision ID: 5cda44932fea
Revises: aa155cadbb94
Create Date: 2024-12-01 03:41:46.165908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cda44932fea'
down_revision = 'aa155cadbb94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_pictures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['t_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_product_attrs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('attr_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('_type', sa.Enum('static', 'dynamic'), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['t_attributes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['t_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_product_attrs')
    op.drop_table('t_pictures')
    # ### end Alembic commands ###
