"""empty message

Revision ID: 662c2866f399
Revises: b58b76a9f234
Create Date: 2024-11-19 09:30:36.249542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '662c2866f399'
down_revision = 'b58b76a9f234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.drop_column('leverl')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leverl', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('level')

    # ### end Alembic commands ###
