"""add last_login field

Revision ID: 7a06af0775bb
Revises: 986bbc804280
Create Date: 2024-12-23 02:36:26.814959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a06af0775bb'
down_revision = '986bbc804280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_orders', schema=None) as batch_op:
        batch_op.drop_constraint('t_orders_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_users', ['user_id'], ['id'])

    with op.batch_alter_table('t_pictures', schema=None) as batch_op:
        batch_op.drop_constraint('t_pictures_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_products', ['product_id'], ['id'])

    with op.batch_alter_table('t_product_attrs', schema=None) as batch_op:
        batch_op.drop_constraint('t_product_attrs_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('t_product_attrs_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_attributes', ['attr_id'], ['id'])
        batch_op.create_foreign_key(None, 't_products', ['product_id'], ['id'])

    with op.batch_alter_table('t_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_users', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    with op.batch_alter_table('t_product_attrs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_product_attrs_ibfk_1', 't_attributes', ['attr_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('t_product_attrs_ibfk_2', 't_products', ['product_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('t_pictures', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_pictures_ibfk_1', 't_products', ['product_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('t_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_orders_ibfk_1', 't_users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
