"""empty message

Revision ID: 986bbc804280
Revises: 5cda44932fea
Create Date: 2024-12-01 22:30:42.328613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986bbc804280'
down_revision = '5cda44932fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('pay_status', sa.Integer(), nullable=True),
    sa.Column('deliver_status', sa.Integer(), nullable=True),
    sa.Column('confirm_status', sa.Integer(), nullable=True),
    sa.Column('confirm_content', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['t_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_express',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('update_time', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['t_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_order_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['t_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['t_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_order_details')
    op.drop_table('t_express')
    op.drop_table('t_orders')
    # ### end Alembic commands ###
