"""init test

Revision ID: 9d043c422ad8
Revises: 1055879123e2
Create Date: 2025-04-17 18:42:32.536141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d043c422ad8'
down_revision = '1055879123e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_attributes', schema=None) as batch_op:
        batch_op.drop_constraint('t_attributes_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_categories', ['category_id'], ['id'])

    with op.batch_alter_table('t_categories', schema=None) as batch_op:
        batch_op.drop_constraint('t_categories_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_categories', ['parent_id'], ['id'])

    with op.batch_alter_table('t_express', schema=None) as batch_op:
        batch_op.drop_constraint('t_express_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_orders', ['order_id'], ['id'])

    with op.batch_alter_table('t_menus', schema=None) as batch_op:
        batch_op.drop_constraint('t_menus_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_menus', ['parent_id'], ['id'])

    with op.batch_alter_table('t_order_details', schema=None) as batch_op:
        batch_op.drop_constraint('t_order_details_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('t_order_details_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_products', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 't_orders', ['order_id'], ['id'])

    with op.batch_alter_table('t_orders', schema=None) as batch_op:
        batch_op.drop_constraint('t_orders_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_users', ['user_id'], ['id'])

    with op.batch_alter_table('t_pictures', schema=None) as batch_op:
        batch_op.drop_constraint('t_pictures_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_products', ['product_id'], ['id'])

    with op.batch_alter_table('t_product_attrs', schema=None) as batch_op:
        batch_op.drop_constraint('t_product_attrs_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('t_product_attrs_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_products', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 't_attributes', ['attr_id'], ['id'])

    with op.batch_alter_table('t_products', schema=None) as batch_op:
        batch_op.drop_constraint('t_products_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('t_products_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('t_products_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_categories', ['cid_one'], ['id'])
        batch_op.create_foreign_key(None, 't_categories', ['cid_three'], ['id'])
        batch_op.create_foreign_key(None, 't_categories', ['cid_two'], ['id'])

    with op.batch_alter_table('t_roles_menus', schema=None) as batch_op:
        batch_op.drop_constraint('t_roles_menus_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('t_roles_menus_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_menus', ['menu_id'], ['id'])
        batch_op.create_foreign_key(None, 't_roles', ['role_id'], ['id'])

    with op.batch_alter_table('t_skus', schema=None) as batch_op:
        batch_op.drop_constraint('t_skus_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_products', ['product_id'], ['id'])

    with op.batch_alter_table('t_spec_templates', schema=None) as batch_op:
        batch_op.drop_constraint('t_spec_templates_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_categories', ['category_id'], ['id'])

    with op.batch_alter_table('t_stock_logs', schema=None) as batch_op:
        batch_op.drop_constraint('t_stock_logs_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_skus', ['sku_id'], ['id'])

    with op.batch_alter_table('t_users', schema=None) as batch_op:
        batch_op.drop_constraint('t_users_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 't_roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_users_ibfk_1', 't_roles', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('t_stock_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_stock_logs_ibfk_1', 't_skus', ['sku_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')

    with op.batch_alter_table('t_spec_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_spec_templates_ibfk_1', 't_categories', ['category_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('t_skus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_skus_ibfk_1', 't_products', ['product_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('t_roles_menus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_roles_menus_ibfk_1', 't_menus', ['menu_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('t_roles_menus_ibfk_2', 't_roles', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('t_products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_products_ibfk_1', 't_categories', ['cid_one'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('t_products_ibfk_2', 't_categories', ['cid_three'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('t_products_ibfk_3', 't_categories', ['cid_two'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('t_product_attrs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_product_attrs_ibfk_1', 't_attributes', ['attr_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('t_product_attrs_ibfk_2', 't_products', ['product_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')

    with op.batch_alter_table('t_pictures', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_pictures_ibfk_1', 't_products', ['product_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')

    with op.batch_alter_table('t_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_orders_ibfk_1', 't_users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('t_order_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_order_details_ibfk_2', 't_products', ['product_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('t_order_details_ibfk_1', 't_orders', ['order_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('t_menus', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_menus_ibfk_1', 't_menus', ['parent_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('t_express', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_express_ibfk_1', 't_orders', ['order_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('t_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_categories_ibfk_1', 't_categories', ['parent_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    with op.batch_alter_table('t_attributes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('t_attributes_ibfk_1', 't_categories', ['category_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')

    # ### end Alembic commands ###
